import 'dotenv/config';
import { writeFile, readFile } from 'node:fs/promises';
import { join } from 'node:path';
import { DspacerClient } from '../src/api-v1/dataspace/source/dspacer.client';
import { DspacerSource } from '../src/api-v1/dataspace/source/dspacer.source';
import {
  ASSET_MAP,
  REFERENCE_ASSETS,
  dcatTypeFromName,
  isNonDataName,
  providerFolderFor,
  suggestMapping,
} from '../src/api-v1/dataspace/source/asset-map';
import {
  DATASET_TYPES,
  DatasetType,
  STATIONS,
} from '../src/api-v1/dataspace/dataspace.constants';
import { bundledDcatTypes } from '../src/api-v1/dataspace/validate-dcat';
import {
  DSPACER_BASE_URL,
  DSPACER_LOGIN_URL,
  DSPACER_PASSWORD,
  DSPACER_USER,
  dspacerConfigured,
} from '../src/api-v1/dataspace/dataspace.constants';

/**
 * Rewrites ASSET_MAP from what the data space currently offers.
 *
 * Assets are republished under new ids — a platform data-loss incident had every
 * dataset re-uploaded with a `_v1.1` suffix — so the table is generated, never
 * transcribed. What makes it trustworthy is that the result is committed: the
 * diff shows exactly which asset changed identity and how it was classified,
 * and a wrong inference is caught in review rather than in a dashboard.
 *
 *   npm run assets:refresh              # report only
 *   npm run assets:refresh -- --write   # rewrite asset-map.ts
 *
 * Anything the heuristic cannot place is listed and left out. Add those by hand.
 */

const MAP_FILE = join(
  __dirname,
  '..',
  'src',
  'api-v1',
  'dataspace',
  'source',
  'asset-map.ts',
);

interface Row {
  id: string;
  name: string;
  provider: string;
  providerFolder: string;
  datasetType: string;
  ocean: string;
  place: string;
}

interface NonDataRow {
  id: string;
  name: string;
  dcatFor: DatasetType | null;
}

function renderMap(
  rows: Row[],
  nonData: NonDataRow[],
  reference: Array<{ id: string; name: string; datasetType: string }>,
): string {
  const byProvider = new Map<string, Row[]>();
  for (const r of [...rows].sort((a, b) =>
    a.providerFolder === b.providerFolder
      ? a.datasetType === b.datasetType
        ? a.place.localeCompare(b.place)
        : a.datasetType.localeCompare(b.datasetType)
      : a.providerFolder.localeCompare(b.providerFolder),
  )) {
    const list = byProvider.get(r.providerFolder) ?? [];
    list.push(r);
    byProvider.set(r.providerFolder, list);
  }

  const lines: string[] = [
    '/** Datasets, by asset id. Regenerate with `npm run assets:refresh -- --write`. */',
    'export const ASSET_MAP: Record<string, MappedAsset> = {',
  ];
  for (const [folder, list] of byProvider) {
    lines.push('');
    lines.push(`  // ---- ${folder}`);
    for (const r of list) {
      lines.push(
        `  '${r.id}': { datasetType: '${r.datasetType}', ocean: '${r.ocean}', ` +
          `place: '${r.place}', providerFolder: '${r.providerFolder}', name: ${JSON.stringify(r.name)} },`,
      );
    }
  }
  lines.push('};');
  lines.push('');
  lines.push('/**');
  lines.push(
    ' * Schema and metadata assets. They are published in the same catalogs as the',
  );
  lines.push(
    ' * datasets and are not data: ingesting them would create assets with no',
  );
  lines.push(' * observations and no location.');
  lines.push(' *');
  lines.push(
    ' * They are not merely skipped, though. Each provider publishes one DCAT document',
  );
  lines.push(
    ' * per dataset, and that document is the schema the dataset is validated against.',
  );
  lines.push(
    ' * `dcatFor` says which type each one describes; null means it is a metadata',
  );
  lines.push(
    ' * document that is not a per-type DCAT, still skipped but claiming nothing.',
  );
  lines.push(' */');
  lines.push('export const NON_DATA_ASSETS: Record<string, NonDataAsset> = {');
  for (const n of [...nonData].sort((a, b) => a.name.localeCompare(b.name))) {
    const dcatFor = n.dcatFor ? `'${n.dcatFor}'` : 'null';
    lines.push(
      `  '${n.id}': { name: ${JSON.stringify(n.name)}, dcatFor: ${dcatFor} },`,
    );
  }
  lines.push('};');
  lines.push('');
  lines.push('/**');
  lines.push(' * The calibration series, by asset id. Regenerate with');
  lines.push(' * `npm run assets:refresh -- --write`.');
  lines.push(' *');
  lines.push(
    ' * They are not measurements of anywhere: one file per category, generated by',
  );
  lines.push(
    ' * `reference-datasets.ts` and published by UP so the engine has something to',
  );
  lines.push(
    ' * fall back on when a request lands where no participant has published. So they',
  );
  lines.push(
    ' * carry no place and no station, and their coordinates are open water in the',
  );
  lines.push(' * Balearic Sea, far from every station.');
  lines.push(' *');
  lines.push(
    ' * Kept apart from ASSET_MAP for one reason above the rest: UP publishes them, so',
  );
  lines.push(
    ' * classifying them by their participant would give them `universal_plastic` and',
  );
  lines.push(
    ' * land them in the **observed** tier — a synthetic series in the middle of the',
  );
  lines.push(
    ' * sea would then reach the map, the dashboard KPIs, the reports and the basin',
  );
  lines.push(
    ' * that archives every analysis. Forcing `ondas_reference` here is what keeps',
  );
  lines.push(
    ' * them out, since the tier is derived from the provider folder.',
  );
  lines.push(' */');
  lines.push('export const REFERENCE_ASSETS: Record<string, DatasetType> = {');
  for (const r of [...reference].sort((a, b) => a.name.localeCompare(b.name))) {
    lines.push(`  '${r.id}': '${r.datasetType}', // ${r.name}`);
  }
  lines.push('};');
  return lines.join('\n');
}

async function main(): Promise<void> {
  if (!dspacerConfigured()) {
    throw new Error(
      'DSPACER_BASE_URL, DSPACER_LOGIN_URL, DSPACER_USER and DSPACER_PASSWORD must be set',
    );
  }
  const write = process.argv.includes('--write');

  const source = new DspacerSource(
    new DspacerClient({
      baseUrl: DSPACER_BASE_URL,
      loginUrl: DSPACER_LOGIN_URL,
      usuario: DSPACER_USER,
      password: DSPACER_PASSWORD,
    }),
  );

  const { entries, warnings } = await source.list();
  for (const w of warnings) console.log(`! ${w}`);
  console.log(`\n${entries.length} assets offered to us\n`);

  const rows: Row[] = [];
  const nonData: NonDataRow[] = [];
  const reference: Array<{ id: string; name: string; datasetType: string }> =
    [];
  const unresolved: Array<{ id: string; name: string; provider: string }> = [];

  for (const entry of entries) {
    const name = entry.ref.label;
    if (isNonDataName(name)) {
      nonData.push({ id: entry.ref.id, name, dcatFor: dcatTypeFromName(name) });
      continue;
    }
    const hint = suggestMapping(name);
    // A calibration series names its category but no place, because it measures
    // nowhere. That is exactly what tells it apart from a dataset whose place we
    // simply failed to read.
    if (/referencia\.?\s*$/i.test(name.trim()) && hint.datasetType) {
      reference.push({ id: entry.ref.id, name, datasetType: hint.datasetType });
      continue;
    }
    if (!hint.datasetType || !hint.place) {
      unresolved.push({ id: entry.ref.id, name, provider: entry.provider });
      continue;
    }
    rows.push({
      id: entry.ref.id,
      name,
      provider: entry.provider,
      providerFolder: providerFolderFor(entry.provider),
      datasetType: hint.datasetType,
      ocean: STATIONS[hint.place].ocean,
      place: hint.place,
    });
  }

  const known = new Set(Object.keys(ASSET_MAP));
  const added = rows.filter((r) => !known.has(r.id));
  const removed = [...known].filter((id) => !rows.some((r) => r.id === id));
  const knownReference = new Set(Object.keys(REFERENCE_ASSETS));
  const addedReference = reference.filter((r) => !knownReference.has(r.id));

  console.log(
    `resolved ${rows.length}  ·  reference ${reference.length}  ·  non-data ${nonData.length}  ·  unresolved ${unresolved.length}`,
  );
  console.log(
    `new ids ${added.length + addedReference.length}  ·  ids no longer offered ${removed.length}\n`,
  );

  for (const r of added)
    console.log(
      `  + ${r.datasetType.padEnd(28)} ${r.place.padEnd(10)} ${r.name}`,
    );
  for (const r of addedReference)
    console.log(
      `  + ${r.datasetType.padEnd(28)} ${'reference'.padEnd(10)} ${r.name}`,
    );
  for (const id of removed) console.log(`  - ${ASSET_MAP[id].name} (${id})`);
  for (const u of unresolved) {
    console.log(
      `  ? ${u.provider}: "${u.name}" (${u.id}) — no reliable hint, add it by hand`,
    );
  }

  // Which types can be validated against the schema their provider published,
  // rather than against the copy bundled in metadata/DCAT. Two types have no
  // bundled copy at all, so for those this is the difference between a column
  // check and none.
  const bundled = new Set(bundledDcatTypes());
  const published = new Map<string, string>();
  for (const n of nonData) {
    if (n.dcatFor && !published.has(n.dcatFor))
      published.set(n.dcatFor, n.name);
  }
  console.log('\nDCAT schemas, by dataset type:');
  for (const type of DATASET_TYPES) {
    const found = published.get(type);
    const mark = found ? '✓' : bundled.has(type) ? '·' : '✗';
    const where = found
      ? `space: ${found}`
      : bundled.has(type)
        ? 'bundled copy only'
        : 'NOTHING — columns of this type are not checked against anything';
    console.log(`  ${mark} ${type.padEnd(28)} ${where}`);
  }
  for (const n of nonData.filter((x) => !x.dcatFor)) {
    console.log(
      `  ? "${n.name}" (${n.id}) — a metadata document of no recognised type; ` +
        `set dcatFor by hand if it is a schema`,
    );
  }

  if (!write) {
    console.log(
      '\nReport only. Re-run with --write to rewrite asset-map.ts, then review the diff.',
    );
    return;
  }

  const current = await readFile(MAP_FILE, 'utf8');
  const start = current.indexOf('/** Datasets, by asset id.');
  // The generated block runs to the end of the last generated table. Anchoring
  // on the previous one would leave a second, stale copy behind it.
  const endMarker =
    'export const REFERENCE_ASSETS: Record<string, DatasetType> = {';
  const markerAt = current.indexOf(endMarker);
  const end = markerAt < 0 ? -1 : current.indexOf('};', markerAt) + 2;
  if (start < 0 || end < 2) {
    throw new Error(
      'could not locate the generated block in asset-map.ts; refusing to rewrite',
    );
  }
  await writeFile(
    MAP_FILE,
    current.slice(0, start) +
      renderMap(rows, nonData, reference) +
      current.slice(end),
    'utf8',
  );
  console.log(`\nRewrote ${MAP_FILE}. Review the diff, then run the tests.`);

  // Losing an asset silently is the failure this whole table exists to prevent.
  if (unresolved.length) process.exit(1);
}

main().catch((e) => {
  console.error(e instanceof Error ? e.message : e);
  process.exit(1);
});
